# Generated by Django 3.1.4 on 2020-12-14 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(verbose_name='更新时间')),
                ('createuser', models.CharField(max_length=30, verbose_name='创建人')),
                ('updateuser', models.CharField(max_length=30, verbose_name='更新人')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('viewnum', models.BigIntegerField(verbose_name='热度')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='ExpModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(verbose_name='更新时间')),
                ('createuser', models.CharField(max_length=30, verbose_name='创建人')),
                ('updateuser', models.CharField(max_length=30, verbose_name='更新人')),
                ('keywords', models.CharField(max_length=1000, verbose_name='关键字')),
                ('viewnum', models.BigIntegerField(verbose_name='热度')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('problem', models.CharField(max_length=2000, verbose_name='问题')),
                ('reason', models.CharField(max_length=2000, verbose_name='原因')),
                ('resolve', models.TextField(verbose_name='解决方法')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expshare.categorymodel', verbose_name='分类')),
            ],
            options={
                'verbose_name': '经验',
                'verbose_name_plural': '经验',
            },
        ),
        migrations.CreateModel(
            name='SharePraise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shareid', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('profession', models.IntegerField(blank=True, null=True, verbose_name='职业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailRegisterCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=300)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(verbose_name='更新时间')),
                ('createuser', models.CharField(max_length=30, verbose_name='创建人')),
                ('updateuser', models.CharField(max_length=30, verbose_name='更新人')),
                ('reason', models.TextField(max_length=2000, verbose_name='原因')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('resolve_note', models.TextField(max_length=500, verbose_name='处理说明')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expshare.expmodel', verbose_name='问题')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
            },
        ),
    ]
