# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('createuser', models.CharField(max_length=30)),
                ('updateuser', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('viewnum', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('createuser', models.CharField(max_length=30)),
                ('updateuser', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=1000)),
                ('viewnum', models.BigIntegerField()),
                ('state', models.IntegerField(default=0)),
                ('problem', models.CharField(max_length=2000)),
                ('reason', models.CharField(max_length=2000)),
                ('resolve', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expshare.CategoryModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
