# Generated by Django 2.1.2 on 2018-11-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('profession', models.IntegerField(verbose_name='职业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='expmodel',
            options={'verbose_name': '经验', 'verbose_name_plural': '经验'},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='createdate',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='createuser',
            field=models.CharField(max_length=30, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=10, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='updatedate',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='updateuser',
            field=models.CharField(max_length=30, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='viewnum',
            field=models.BigIntegerField(verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expshare.CategoryModel', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='createdate',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='createuser',
            field=models.CharField(max_length=30, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='keywords',
            field=models.CharField(max_length=1000, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='problem',
            field=models.CharField(max_length=2000, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='reason',
            field=models.CharField(max_length=2000, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='resolve',
            field=models.TextField(verbose_name='解决方法'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='updatedate',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='updateuser',
            field=models.CharField(max_length=30, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='expmodel',
            name='viewnum',
            field=models.BigIntegerField(verbose_name='热度'),
        ),
    ]
