# Generated by Django 2.1.2 on 2018-11-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expshare', '0002_auto_20181107_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(verbose_name='更新时间')),
                ('createuser', models.CharField(max_length=30, verbose_name='创建人')),
                ('updateuser', models.CharField(max_length=30, verbose_name='更新人')),
                ('reason', models.TextField(max_length=2000, verbose_name='原因')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('resolve_note', models.TextField(max_length=500, verbose_name='处理说明')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expshare.ExpModel', verbose_name='问题')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
