# Generated by Django 2.1.2 on 2018-11-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expshare', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '反馈', 'verbose_name_plural': '反馈'},
        ),
    ]
