# Generated by Django 2.1.2 on 2018-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expshare', '0004_auto_20181108_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePraise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shareid', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
