# Generated by Django 2.1.2 on 2018-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expshare', '0005_sharepraise'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
    ]
