INSERT INTO `auth_permission` VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission` VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission` VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission` VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO `auth_permission` VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission` VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission` VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission` VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO `auth_permission` VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission` VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission` VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission` VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO `auth_permission` VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission` VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission` VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission` VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO `auth_permission` VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission` VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission` VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission` VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO `auth_permission` VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission` VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission` VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission` VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO `auth_permission` VALUES (25, 'Can add category model', 7, 'add_categorymodel');
INSERT INTO `auth_permission` VALUES (26, 'Can change category model', 7, 'change_categorymodel');
INSERT INTO `auth_permission` VALUES (27, 'Can delete category model', 7, 'delete_categorymodel');
INSERT INTO `auth_permission` VALUES (28, 'Can view category model', 7, 'view_categorymodel');
INSERT INTO `auth_permission` VALUES (29, 'Can add exp model', 8, 'add_expmodel');
INSERT INTO `auth_permission` VALUES (30, 'Can change exp model', 8, 'change_expmodel');
INSERT INTO `auth_permission` VALUES (31, 'Can delete exp model', 8, 'delete_expmodel');
INSERT INTO `auth_permission` VALUES (32, 'Can view exp model', 8, 'view_expmodel');
INSERT INTO `auth_permission` VALUES (33, 'Can add test', 9, 'add_test');
INSERT INTO `auth_permission` VALUES (34, 'Can change test', 9, 'change_test');
INSERT INTO `auth_permission` VALUES (35, 'Can delete test', 9, 'delete_test');
INSERT INTO `auth_permission` VALUES (36, 'Can view test', 9, 'view_test');
INSERT INTO `auth_permission` VALUES (41, 'Can add user extends', 21, 'add_userextends');
INSERT INTO `auth_permission` VALUES (42, 'Can change user extends', 21, 'change_userextends');
INSERT INTO `auth_permission` VALUES (43, 'Can delete user extends', 21, 'delete_userextends');
INSERT INTO `auth_permission` VALUES (44, 'Can view user extends', 21, 'view_userextends');
INSERT INTO `auth_permission` VALUES (45, 'Can add feedback', 22, 'add_feedback');
INSERT INTO `auth_permission` VALUES (46, 'Can change feedback', 22, 'change_feedback');
INSERT INTO `auth_permission` VALUES (47, 'Can delete feedback', 22, 'delete_feedback');
INSERT INTO `auth_permission` VALUES (48, 'Can view feedback', 22, 'view_feedback');
INSERT INTO `auth_permission` VALUES (49, 'Can add share praise', 23, 'add_sharepraise');
INSERT INTO `auth_permission` VALUES (50, 'Can change share praise', 23, 'change_sharepraise');
INSERT INTO `auth_permission` VALUES (51, 'Can delete share praise', 23, 'delete_sharepraise');
INSERT INTO `auth_permission` VALUES (52, 'Can view share praise', 23, 'view_sharepraise');
